"""
External Render Watchdog – monitors given PID and alerts via Pushover.
Start syntax (auto-generated by the add-on):
  python watchdog_core.py <PID> <TOKEN> <USER>
"""

import os, sys, time, requests, subprocess, signal, platform
PID, PUSH_TOKEN, PUSH_USER = int(sys.argv[1]), sys.argv[2], sys.argv[3]

def process_alive(pid: int) -> bool:
    """plattf-unabhängig testen, ob Prozess existiert"""
    try:
        if platform.system() == "Windows":
            subprocess.check_output(["tasklist", "/fi", f"PID eq {pid}"])
        else:
            os.kill(pid, 0)
        return True
    except Exception:
        return False

def send_push(title, msg):
    try:
        r = requests.post("https://api.pushover.net/1/messages.json", data={
            "token": PUSH_TOKEN, "user": PUSH_USER,
            "title": title, "message": msg})
        if r.status_code != 200:
            print("Push failed:", r.status_code, r.text)
    except Exception as e:
        print("Push error:", e)

while True:
    if not process_alive(PID):
        send_push("Blender abgestürzt", f"PID {PID} wurde unerwartet beendet.")
        break
    time.sleep(1)